<?php
$default = [
    'ua' => 'UA-XXXXXXXX-XX',
    'ad_banners' => false,
    'recaptcha' => true,
    'website_name' => 'BoatGest',
    'website_url' => 'http://www.boatgest.com',
    'website_youboat_url' => 'http://localhost:8000',
    'root' => 'youboat-www_website',
    'tagline' => 'New and Used boats for sale',
    'country_code' => 'GB',
    'currency' => '£',
    'default_metas_title' => 'Client Management tool, CRM and sales support for the Pros. Boat',
    'default_metas_description' => '',
    'default_metas_keywords' => '',
    'phone' => '+44-07-5654-24955',

    'MAIL_NO_REPLY_EMAIL' => 'services@youboat.com',
    'MAIL_NO_REPLY_NAME' => 'Services',
    'MAIL_CONTACT_EMAIL' => 'contact@youboat.com',
    'MAIL_CONTACT_NAME' => 'Contact',

    'email' => 'youboat.uk@gmail.com',
    //'email' => 'youboatuk@rivamedia.fr',

    'contact_email' => 'youboat.uk@gmail.com',

    'emails_bcc' => 'contact@rivamedia.fr',
    //'country_manager_email' => 'emmanuel.deiller.rivamedia+country_manager_email@gmail.com',
    'country_manager_email' => 'youboat.uk+country_manager@gmail.com',
    'address' => '',

    'facebook' => 'https://www.facebook.com/youboatcom/',
    'facebook_widget' => false,
    'twitter' => 'https://twitter.com/youboat_com',
    'twitter_widget' => false,
    'theme' => [
        //'color'=> 1, /* 1 to 12*/
        'tpl' => [
            'header_version' => ['header-v1'],
            //'header_version' => ['header-v2'],
            //'header_version' => ['header-v3'],
            //'header_version' => ['header-v4'],
            'hero_area' => [
                'flex_slider' => true,
                'search_over_slider' => true,
                'owl_carousel' => false,
                'revolution_slider' => false,
            ],
            'cookie_legacy' => false,
            'utility_bar' => true,
            'currency_nav' => false,
            'language_nav' => true,
        ],
        'vendor' => [
            'select2' => true,
            'google_map' => true,
            'modernizr' => true,
            'flex_slider' => true,
            'owl_carousel' => true,
            'pretty_photo' => true,
            'waypoints' => false,
            'revolution_slider' => false,
            'password_checker' => true,
        ],
        'ui_plugins' => [
            'fitvids' => false,
            'superfish' => true, // set hoverintent to true if superfish
            'scroll_to' => true,
            'count_to' => false,
            'bootstrap_select' => true,
            'bootstrap_timepicker' => false,
            'bootstrap_datepicker' => false,
        ],
        'helper_plugins' => [
            'hoverintent' => true, // set hoverintent to true if superfish
            'sticky' => true,
            'imagesloaded' => false, // set imagesloaded to true if isotope
            'isotope' => false, // set imagesloaded to true if isotope
            'touch_swipe' => false,
            'throttle_debounce' => false,
            'localscroll' => false,
            'easing' => true,
            'scroll_to' => false,
            'cookie' => false,
            'swipe' => false,
            'appear' => true,
            'parallax' => true,
            'retina' => false,
            'transit' => false,
            'mousewheel' => false,
            'tweetie' => false,
        ],
    ],
    'vendor' => [
        'bootstrap_datetimepicker' => false,
        'select2' => true,
    ],
    'twitter_api' => [
        'CONSUMER_KEY' => 'JKO6zJIgNCKWUtUR8G8SL6W3x',
        'CONSUMER_SECRET' => 'wnF8juBaevW46HCoCb8O0jT6pb9LdOE4BKCkcQBFBO438iv3RR',
        'ACCESS_TOKEN' => '722416932444585984-G2bF9dTFtnkcm1eifQp70H1NLZNKLGI',
        'ACCESS_SECRET' => 'Kd0sR0HswefvdlUm6arDN8kEnc66aLH4vkbX1uZ2g8gNo',
        'owner' => 'youboat_com',
        'owner_id' => '722416932444585984'
    ],
    'country_code' => 'GB',
    'locations' => [
        'regions' => [
            'south_east' => [
                'name'=> 'South East',
                'county' => [
                    'Hampshire',
                    'Surrey',
                    'Kent',
                    'West Sussex',
                    'East Sussex',
                    'Isle of Wight',
                    'Sussex',
                ]
            ],
            'south_west' => [
                'name'=> 'South West',
                'county' => [
                    'Dorset',
                    'Devon',
                    'Cornwall',
                    'Gloucestershire',
                    'Somerset',
                    'Avon',
                    'Bristol',
                    'Wiltshire',
                    'Isles of Scilly',
                ]
            ],
            'eastern' => [
                'name'=> 'Eastern',
                'county' => [
                    'Essex',
                    'Norfolk',
                    'Cambridgeshire',
                    'Suffolk',
                    'Bedfordshire',
                    'Hertfordshire',
                ]
            ],
            'north_east' => [
                'name'=> 'North East',
                'county' => [
                    'Yorkshire',
                    'North Yorkshire',
                    'South Yorkshire',
                    'Northumberland',
                    'Cleveland',
                    'Humberside',
                    'East Yorkshire',
                    'Tyne & Wear',
                    'West Yorkshire',
                    'Tyne And Wear',
                    'County Durham',
                    'Durham',
                ]
            ],
            'wales' => [
                'name'=> 'Wales',
                'county' => [
                    'Gwynedd',
                    'Pembrokeshire',
                    'West Glamorgan',
                    'Glamorgan',
                    'Conwy',
                    'South Wales',
                    'Dyfed',
                    'Clwyd',
                    'South Glamorgan',
                    'Flintshire',
                    'Monmouthshire',
                    'Carmarthenshire',
                    'Isle of Anglesey',
                    'North Wales',
                    'Gwent',
                    'Mid Glamorgan',
                    'Powys',
                    'Denbighshire',
                    'Mid Wales',
                ]
            ],
            'north_west' => [
                'name'=> 'North West',
                'county' => [
                    'Cumbria',
                    'Lancashire',
                    'Greater Manchester',
                    'Liverpool',
                    'Merseyside',
                    'Cheshire',
                ]
            ],
            'east_midlands' => [
                'name'=> 'East Midlands',
                'county' => [
                    'Leicestershire',
                    'Nottinghamshire',
                    'Lincolnshire',
                    'Derbyshire',
                    'Northamptonshire',
                    'Rutland',
                ]
            ],
            'thames_valley' => [
                'name'=> 'Thames Valley',
                'county' => [
                    'Berkshire',
                    'London',
                    'Middlesex',
                    'Buckinghamshire',
                    'Oxfordshire',
                ]
            ],
            'channel_islands' => [
                'name'=> 'Channel Islands',
                'county' => [
                    'Guernsey',
                    'Jersey',
                ]
            ],
            'scotland' => [
                'name' => 'Scotland',
                'county' => [
                    'Strathclyde',
                    'Glasgow',
                    'Edinburgh',
                    'Highland',
                    'Aberdeenshire',
                    'Argyll',
                    'Angus',
                    'Perthshire',
                    'Ayrshire',
                    'Dunbartonshire',
                    'Renfrewshire',
                    'Fife',
                    'Dumfries & Galloway',
                    'Inverness-shire',
                    'Argyllshire',
                    'East Lothian',
                    'Grampian',
                    'Central Scotland',
                    'Morayshire',
                    'West Lothian',
                    'Isle Of Bute',
                    'Isle of Skye',
                    'Ross-shire',
                    'Scottish Borders',
                    'Shetland',
                    'Stirlingshire',
                    'Dumfriesshire',
                    'Falkirk',
                    'Isle Of Lewis',
                    'Isle of Arran',
                    'Isle of Rum',
                    'Lanarkshire',
                    'Lothian',
                    'Midlothian',
                    'Orkney',
                    'Peeblesshire',
                    'Stirling',
                    'Tayside',
                ]
            ],
            'west_midlands' => [
                'name'=> 'West Midlands',
                'county' => [
                    'Herefordshire',
                    'Shropshire',
                    'Staffordshire',
                    'Warwickshire',
                    'Worcestershire',
                ]
            ],
            'northern_ireland' => [
                'name'=> 'Northern Ireland',
                'county' => [
                    'County Londonderry',
                    'County Down',
                    'Antrim',
                    'Armagh',
                    'County Antrim',
                    'Fermanagh',
                ]
            ],
            'isle_of_man' => [
                'name'=> 'Isle of Man',
                'county' => [
                    'Isle of Man',
                ]
            ],
            'southern_ireland' => [
                'name'=> 'Southern Ireland',
                'county' => [
                    'Cork',
                    'Galway',
                    'Cavan',
                ]
            ],
            'ireland' => [
                'name'=> 'Ireland',
                'county' => [
                    'Meath',
                    'Monaghan',
                    'Offaly',
                    'Waterford',
                    'Westmeath',
                    'Wexford',
                ]
            ],
        ],
        'counties' => [
            '1'=>'Aberdeenshire',
            '2'=>'Angus',
            '3'=>'Antrim',
            '4'=>'Argyll',
            '5'=>'Argyllshire',
            '6'=>'Armagh',
            '7'=>'Avon',
            '8'=>'Ayrshire',
            '9'=>'Banffshire',
            '10'=>'Bedfordshire',
            '11'=>'Berkshire',
            '12'=>'Berwickshire',
            '13'=>'Bristol',
            '14'=>'Buckinghamshire',
            '15'=>'Caithness',
            '16'=>'Cambridgeshire',
            '17'=>'Carlow',
            '18'=>'Carmarthenshire',
            '19'=>'Cavan',
            '20'=>'Central Scotland',
            '21'=>'Channel Islands',
            '22'=>'Channel Isles',
            '23'=>'Cheshire',
            '24'=>'Clackmannanshire',
            '25'=>'Clare',
            '26'=>'Cleveland',
            '27'=>'Clwyd',
            '28'=>'Co. Durham',
            '29'=>'Conwy',
            '30'=>'Cork',
            '31'=>'Cornwall',
            '32'=>'County Antrim',
            '33'=>'County Armagh',
            '34'=>'County Down',
            '35'=>'County Durham',
            '36'=>'County Fermanagh',
            '37'=>'County Londonderry',
            '38'=>'County Tyrone',
            '39'=>'Cumbria',
            '40'=>'Denbighshire',
            '41'=>'Derbyshire',
            '42'=>'Derry',
            '43'=>'Devon',
            '44'=>'Donegal',
            '45'=>'Dorset',
            '46'=>'Down',
            '47'=>'Dublin',
            '48'=>'Dumfries & Galloway',
            '49'=>'Dumfriesshire',
            '50'=>'Dunbartonshire',
            '51'=>'Dungannon',
            '52'=>'Durham',
            '53'=>'Dyfed',
            '54'=>'East Lothian',
            '55'=>'East Sussex',
            '56'=>'East Yorkshire',
            '57'=>'Edinburgh',
            '58'=>'Eilean Siar',
            '59'=>'Essex',
            '60'=>'Falkirk',
            '61'=>'Fermanagh',
            '62'=>'Fife',
            '63'=>'Flintshire',
            '64'=>'Galway',
            '65'=>'Glamorgan',
            '66'=>'Glasgow',
            '67'=>'Gloucestershire',
            '68'=>'Grampian',
            '69'=>'Greater Manchester',
            '70'=>'Guernsey',
            '71'=>'Gwent',
            '72'=>'Gwynedd',
            '73'=>'Hampshire',
            '74'=>'Herefordshire',
            '75'=>'Hertfordshire',
            '76'=>'Highland',
            '77'=>'Humberside',
            '78'=>'Huntingdonshire',
            '79'=>'Inverness-shire',
            '80'=>'Isle of Anglesey',
            '81'=>'Isle of Arran',
            '82'=>'Isle Of Barra',
            '83'=>'Isle Of Benbecula',
            '84'=>'Isle Of Bute',
            '85'=>'Isle of Canna',
            '86'=>'Isle Of Coll',
            '87'=>'Isle Of Colonsay',
            '88'=>'Isle of Cumbrae',
            '89'=>'Isle of Eigg',
            '90'=>'Isle Of Gigha',
            '91'=>'Isle Of Harris',
            '92'=>'Isle Of Iona',
            '93'=>'Isle Of Islay',
            '94'=>'Isle Of Jura',
            '95'=>'Isle Of Lewis',
            '96'=>'Isle of Man',
            '97'=>'Isle Of Mull',
            '98'=>'Isle Of North Uist',
            '99'=>'Isle of Rum',
            '100'=>'Isle Of Scalpay',
            '101'=>'Isle of Skye',
            '102'=>'Isle Of South Uist',
            '103'=>'Isle Of Tiree',
            '104'=>'Isle of Wight',
            '105'=>'Isles of Scilly',
            '106'=>'Jersey',
            '107'=>'Kent',
            '108'=>'Kerry',
            '109'=>'Kildare',
            '110'=>'Kilkenny',
            '111'=>'Kincardineshire',
            '112'=>'Kinross-Shire',
            '113'=>'Kirkcudbrightshire',
            '114'=>'Lanarkshire',
            '115'=>'Lanarkshire (Scot)',
            '116'=>'Lancashire',
            '117'=>'Laois',
            '118'=>'Leicestershire',
            '119'=>'Leitrim',
            '120'=>'Limerick',
            '121'=>'Lincolnshire',
            '122'=>'Liverpool',
            '123'=>'London',
            '124'=>'Longford',
            '125'=>'Lothian',
            '126'=>'Louth',
            '127'=>'Mayo',
            '128'=>'Meath',
            '129'=>'Merseyside',
            '130'=>'Mid Glamorgan',
            '131'=>'Mid Wales',
            '132'=>'Middlesex',
            '133'=>'Midlothian',
            '134'=>'Monaghan',
            '135'=>'Monmouthshire',
            '136'=>'Morayshire',
            '137'=>'Nairnshire',
            '138'=>'Norfolk',
            '139'=>'North Humberside',
            '140'=>'North Wales',
            '141'=>'North Yorkshire',
            '142'=>'Northamptonshire',
            '143'=>'Northern Ireland',
            '144'=>'Northumberland',
            '145'=>'Nottinghamshire',
            '146'=>'Offaly',
            '147'=>'Orkney',
            '148'=>'OverSeas',
            '149'=>'Oxfordshire',
            '150'=>'Peeblesshire',
            '151'=>'Pembrokeshire',
            '152'=>'Perthshire',
            '153'=>'Powys',
            '154'=>'Renfrewshire',
            '155'=>'Ridings',
            '156'=>'Roscommon',
            '157'=>'Ross-shire',
            '158'=>'Roxburghshire',
            '159'=>'Rutland',
            '160'=>'Scottish Borders',
            '161'=>'Selkirkshire',
            '162'=>'Shetland',
            '163'=>'Shetland Islands',
            '164'=>'Shropshire',
            '165'=>'Sligo',
            '166'=>'Somerset',
            '167'=>'South Glamorgan',
            '168'=>'South Humberside',
            '169'=>'South Wales',
            '170'=>'South Yorkshire',
            '171'=>'Southern Ireland',
            '172'=>'Staffordshire',
            '173'=>'Stirling',
            '174'=>'Stirlingshire',
            '175'=>'Strathclyde',
            '176'=>'Suffolk',
            '177'=>'Surrey',
            '178'=>'Sussex',
            '179'=>'Sutherland',
            '180'=>'Tayside',
            '181'=>'Tipperary',
            '182'=>'Tyne & Wear',
            '183'=>'Tyne And Wear',
            '184'=>'Tyrone',
            '185'=>'W Glam',
            '186'=>'Warwickshire',
            '187'=>'Waterford',
            '188'=>'West Glamorgan',
            '189'=>'West Lothian',
            '190'=>'West Midlands',
            '191'=>'West Sussex',
            '192'=>'West Yorkshire',
            '193'=>'Western Isles',
            '194'=>'Westmeath',
            '195'=>'Wexford',
            '196'=>'Wicklow',
            '197'=>'Wigtownshire',
            '198'=>'Wiltshire',
            '199'=>'Worcestershire',
            '200'=>'Yorkshire'
        ],
    ],
    'stripe' => [
        'plan_pay_url' => 'https://uk.youboat.com/pay/',
        'charge_description' => 'Unlimited UK Offer',
        'charge_amount' => 29,
        'pay_currency' => 'gbp',
        'pay_locale' => 'en',
    ]
];
return [
    'uk'  => $default,
    'gb'  => $default,
    'dev'  => $default
];
