<?php

namespace AppBundle\Repository;

/**
 * Category_eventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryEventRepository extends \Doctrine\ORM\EntityRepository
{
}
