<?php

namespace AppBundle\Repository;

/**
 * Circle_userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CircleUserRepository extends \Doctrine\ORM\EntityRepository
{

}
