<?php

namespace AppBundle\Repository;

/**
 * CloudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CloudRepository extends \Doctrine\ORM\EntityRepository
{
}
