<?php

namespace AppBundle\Repository;


/**
 * Connected_objectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConnectedObjectRepository extends \Doctrine\ORM\EntityRepository
{

}
