<?php

namespace AppBundle\Repository;

/**
 * Data_objectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataObjectRepository extends \Doctrine\ORM\EntityRepository
{
}
