<?php

namespace AppBundle\Repository;

/**
 * Object_accessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectAccessRepository extends \Doctrine\ORM\EntityRepository
{
}
