<?php

namespace AppBundle\Repository;

/**
 * Type_objectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeObjectRepository extends \Doctrine\ORM\EntityRepository
{
}
