<?php

    return [
        'title' => "CONDITIONS GENERALES DE VENTE ET D'UTILISATION",

        'article_1_title' => "1. Préambule",
        'article_1_text' => "Le site Youboat.fr a pour objet la mise en relation des acquéreurs et cédants de bateaux, moteurs de bateaux, accessoires, accastillages, places de ports, ...etc. La société n'intervient pas dans la finalisation effective des transactions et n'est pas assimilée à ce titre à un intermédiaire commercial. La mise en ligne d'annonces de recherche dans le domaine du Nautisme est gratuite pour les particuliers. L'inscription pour recevoir une alerte email est gratuite. Toute mise en relation ou d'annonce sur le site Youboat.fr implique de la part des utilisateurs l'acceptation des présentes conditions générales. L'acceptation des présentes conditions ne peut être que pleine et entière. Toute acceptation sous réserve est considérée comme nulle et non avenue. En utilisant le site Youboat.fr pour mettre en ligne une annonce de cession ou de recherche, l'utilisateur déclare se conformer aux lois et règlements en vigueur dans son pays et en France. Les relations entre l'utilisateur et la société sont régies par la loi Française.",

        'article_2_title' => "2. Inscription sur le site",
        'article_2_text' => "L'inscription sur le site implique de la part de l'annonceur sa qualité, capacité et autorisations requises pour publier une annonce. Lors de son inscription en ligne sur le site, l'annonceur doit remplir un formulaire de recueil de données personnelles. L'annonceur garantit que toutes les informations qu'il fournit dans le formulaire sont exactes et ne sont entachées d'aucun caractère trompeur ou malhonnête. Le webmaster du site se réserve le droit le compléter, modifier ou effacer à tout moment et sans préavis le contenu des champs d'inscription, notamment ceux permettant d'identifier directement ou indirectement les coordonnées de l'annonceur ou du bien proposé. Le webmaster se réserve par ailleurs la faculté de modifier les caractéristiques des annonces passées sur le site ainsi que la sélection de la photo apparaissant dans l'annonce de présentation. La validation et la mise en ligne des annonces et de leurs modifications sont effectuées sous 24 heures ouvrées sauf cas exceptionnel. En aucun cas la société ne pourra être tenue responsable d'un retard de publication. L'annonceur a la faculté de modifier les éléments de son annonce, notamment en ce qui concerne le prix de vente du bien proposé ou les critères du bien recherché. Ces modifications faisant l'objet d'une validation par le webmaster. L'annonceur accepte de recevoir les courriels informatifs du site Youboat.fr sans les considérer comme intrusifs. Il s'engage à répondre aux demandes régulières de mise à jour, notamment sur la validité de sa mise en vente ou de sa recherche. L'annonceur doit impérativement vérifier son annonce dès sa mise en ligne et informer la société de toute inexactitude avec la réalité du bien ou profil mis en ligne. L'annonceur s'engage à se désinscrire du site dès lors que son bien ne serait plus à la vente ou que sa recherche ne serait plus effective.",

        'article_3_title' => "3. Demande de mise en relation",
        'article_3_text' => "Les mises en relation sont enregistrées sur le site Youboat.fr. Sauf preuve contraire, les données enregistrées par la société constituent la preuve de l'ensemble des transactions conclues avec ses clients. Il est précisé que l'utilisateur est seul responsable :<br>
- de l'exactitude des informations qu'il communique à la société lors de sa commande (nom, prénom, coordonnées, description du bien ou de la recherche, etc...)<br>
- de l'utilisation qu'il fait des coordonnées obtenues lors de sa commande.<br>
La société n'est aucunement responsable de l'annonce passée par le cédant ou l'acquéreur et ne pourra être poursuivi pour des informations fausses, erronées ou périmées. Le client est invité à signaler à la société toute annonce erronée ou périmée par courriel à l'adresse suivante : contact@rivamedia.fr",

        'article_4_title' => "4. Demande d'alertes email",
        'article_4_text' => "Les demandes d'alertes email sont enregistrées sur le site Youboat.fr et validés. Les critères de recherche sont modifiables a tout instant depuis l'url www.youboat.fr/recherche-bateau.html. L'utilisateur peut de désinscrire à tout moment du service gratuit d'alerte mail. La société n'est aucunement responsable du nombre de mail d'alerte reçus et ne pourra être poursuivie pour des informations fausses, erronées ou périmées.",

        'article_5_title' => "5. Tarif et paiement :",
        'article_5_text' => "VOUS ETES PARTICULIER<br>
Le dépôt d'une annonce de recherche dans la Boat on Demand est gratuit. Votre annonce sera diffusée jusqu'au moment où vous aurez trouvé le bien recherché. Les renseignements ne sont accessibles que sur inscription, cela permet de garder la confidentialité. Vos coordonnées complètes s'affichent directement sur votre annonce.<br>
Déposez votre annonce pour VENDRE votre bien jusqu'à la vente : 29 € - Tarifs applicables au 18/10/2012. Le paiement du prix s'effectue à la commande par carte bancaire (Visa, Master-Card ,). A cet effet, la société a mis en place un système de paiement sécurisé.<br>
Déposez votre annonce pour RECHERCHER un bien GRATUITEMENT Déposez des alerte email GRATUITEMENT<br>
VOUS ETES PROFESSIONNEL<br>
Contactez notre service commercial au 02 38 75 99 41 ou par mail : contact@rivamedia.fr afin d'obtenir une offre sur mesure. Pour les insertions publicitaires, veuillez contacter notre service publicité au 02 38 75 99 41 ou par mail : contact@rivamedia.fr
",

        'article_6_title' => "6. Accès aux coordonnées",
        'article_6_text' => "La société décline toute responsabilité quant à la validité et à l'exactitude des informations communiquées par les auteurs des annonces.",

        'article_7_title' => "7. Données à caractère personnel et Confidentialité",
        'article_7_text' => "La société s'engage à ne communiquer les données collectées qu'aux personnes ayant eu l'intention d'en faire acquisition dans le cadre des mises en relation. La société se réserve le droit de communiquer les données nominatives collectées à toute entreprise extérieure liée à nous contractuellement. Le personnel de la société a accès à vos données personnelles dans la limite de leurs attributions. Afin de répondre aux obligations légales, nous pourrions être également amenés à transmettre vos données personnelles aux organismes publics dûment habilités qui nous en feraient la demande. L'inscription sur notre site et la communication de vos données personnelles vaut consentement express pour l'utilisation de celles-ci à des fins commerciales.",

        'article_8_title' => "8. Absence de Garantie",
        'article_8_text' => "Les coordonnées livrées lors d'une commande de mise en relation sont communiquées telles que les auteurs des annonces les ont enregistrées. Malgré nos vérifications sur leurs validités, le site ne saurait garantir l'exactitude des informations présentées sur le site. En conséquence, ces données ne donnent lieu à aucune garantie de la part de la société, qui ne saurait voir sa responsabilité recherchée à quelque titre que ce soit, notamment en raison d'une utilisation infructueuse ou du fait de leur validité.",

        'article_9_title' => "9. Suppression des annonces",
        'article_9_text' => "Il n'y a pas de durée maximum de publication des annonces. Cependant nous vous remercions de bien vouloir supprimer celle-ci lorsque vous aurez trouvé ou vendu votre bien. Vous pouvez supprimer votre annonce à tous moment en allant sur la rubrique « mon compte ». Nous vous expédierons régulièrement un mail vous demandant de bien vouloir confirmer la validité de votre offre ou de votre recherche. Si vous ne répondez pas à cette sollicitation, et après relance de notre part, le site se réserve le droit de supprimer votre annonce.",

        'article_10_title' => "10. Disfonctionnement.",
        'article_10_text' => "Sont contractuellement assimilés à des cas de force majeure et constitueront des causes d'extinction ou de suspension des obligations de la société, sans recours du client, les incidents techniques (panne de téléphone, panne de réseau, d'informatique, coupure EDF, etc...), la défaillance des opérateurs de télécommunication et/ou des services postaux, l'incendie, le bris de machines, la grève totale ou partielle, les décisions administratives, le fait de tiers et tout événement extérieur qui serait de nature à retarder, à empêcher ou à rendre excessivement onéreuse l'exécution des engagements souscrits dans le cadre des présentes. La société est amenée à procéder régulièrement à des maintenances interrompant momentanément l'accessibilité au site et ne saurait en être tenu responsable.",

        'article_11_title' => "11. Dommages intérêts",
        'article_11_text' => "La responsabilité de la société, à quelque titre que ce soit, se limite expressément à la livraison des coordonnées par la mise en relation et ne couvre en aucun cas l'indemnisation ou la réparation du manque à gagner, des coûts, ni de tout autre dommage ou préjudice qui pourrait être invoqué par le client. La société n'est pas tenue de vérifier la qualité, la cessibilité, la conformité des bien annoncés ni de la capacité des acquéreurs à s'acquitter du prix de vente. Il est de l'unique responsabilité des cédants et acquéreurs, traitant sans intermédiation, de vérifier toutes les informations nécessaires avant toute conclusion d'affaire.",

        'article_12_title' => "12. Propriété intellectuelle et d'auteur",
        'article_12_text' => "Tous les droits de reproduction totale ou partielle du site Youboat.fr pour un usage autre que privé est strictement interdit. Les textes, illustrations, images et représentations iconographiques contenus dans le site Youboat.fr, sont sa propriété exclusive, conformément aux dispositions du Code de la propriété intellectuelle, ainsi qu'aux conventions internationales en vigueur. La marque Youboat est déposée à l'INPI et fait l'objet d'un copyright. Toute utilisation sans autorisation fera l'objet de poursuites.",

        'article_13_title' => "13. Liens et publicité",
        'article_13_text' => "La société n'est en aucune manière responsable des sites édités par des tiers que le client pourrait être amené à consulter à partir des liens et publicités existant sur le site et Youboat.fr. La société exclut notamment toute garantie en ce qui concerne le contenu de ces sites, ainsi que les informations, produits et/ou services qu'ils diffusent. En conséquence, il appartient à l'utilisateur de prendre toutes précautions et mesures de protection utiles en cas d'utilisation de ces liens, notamment contre une éventuelle attaque de virus.",

        'article_14_title' => "14. Informatique et libertés",
        'article_14_text' => "Les informations recueillies sur le site Youboat.fr font l'objet d'un traitement informatique destiné au croisement des critères de recherche. La société peut toutefois être amenée à revendre ces informations. Conformément à la loi « informatique et libertés » du 6 janvier 1978, le client bénéficie d'un droit d'accès et de rectification aux informations qui le concernent. S'il souhaite exercer ce droit et obtenir communication des informations le concernant, il peut s'adresser à Riva Media - 37 rue des Murlins 45000 ORLEANS ou par mail à l'adresse : contact@rivamedia.fr",

        'article_15_title' => "15. Validité et modifications",
        'article_15_text' => "La société se réserve le droit de modifier à tout moment les présentes conditions générales et d'utilisation qui s'appliqueraient immédiatement aux utilisateurs du site. Les utilisateurs sont invités à vérifier régulièrement les conditions qui s'appliquent à eux. La version applicable ce jour est celle du 01/04/2011.La société se réserve le droit de modifier l'aspect, les fonctionnalités et les conditions d'utilisation du site et ce sans possibilité de recours des utilisateurs.",

        'article_16_title' => "16. Litiges - Contestation",
        'article_16_text' => "Toutes relations entre la société et ses clients sont régies par le droit français. Toutes contestations ou difficultés ainsi, plus généralement, que tout litige avec les se rapportant à l'interprétation ou à l'exécution des présentes seront de la compétence exclusive du Tribunal de commerce de PARIS.",

        'article_17_title' => "17. Service clientèle",
        'article_17_text' => "Toutes demandes d'informations et/ou réclamations peuvent être présentées à la société : Par courrier postal adressé au siège social : à Riva Media - 37 rue des Murlins 45000 ORLEANS ou par courrier électronique à l'adresse : contact@rivamedia.fr",

        'article_18_title' => "18. Utilisation de cookies",
        'article_18_text' => "Ce site utilise Google Analytics. En continuant à naviguer, vous nous autorisez à déposer des cookies à des fins de mesure d'audience. Les boutons de partage sur les réseaux sociaux utilisent également des cookies générés par les réseaux sociaux eux-mêmes. La société Rivamedia ne peut être tenue responsable de l'utilisation qui est faite de ces cookies. Certaines pages du site déposent des cookies de traçage sur votre ordinateur à des fins de ciblage publicitaire. En continuant à naviguer vous acceptez le dépôt et l'utilisation de ces cookies. Les cookies en eux-mêmes ne peuvent servir à découvrir l'identité de l'utilisateur. Si vous ne souhaitez pas que youboat.fr ait accès aux cookies, votre navigateur vous permet de refuser ou de désactiver l'utilisation de cookies ; toutefois, veuillez noter que les cookies peuvent être nécessaires pour permettre à youboat.fr d'améliorer votre utilisation du Site. Les fonctionnalités de chaque navigateur étant différentes, veuillez vous référer à la rubrique « Aide » de votre navigateur pour de plus amples informations sur la façon de refuser ou désactiver l'utilisation de cookies.",

    ];